sonar.organization=ankittomar0207
sonar.projectKey=ankittomar0207_Jenkins-Zero-To-Hero
sonar.projectName=Jenkins-Zero-To-Hero
sonar.host.url=https://sonarcloud.io
sonar.qualitygate.wait=false
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.js
sonar.sourceEncoding=UTF-8
